### PR TITLE
Update 00-rpc-providers.md

### PR DESCRIPTION
**Pull request by AnnaNodes**
Hello,

We are a Solana node provider NOWNodes.io.

Could you please add us to the node providers list?

### CODE REVIEW

**Comment by lorisleiva** [comment]
Hi there, thanks for the PR!

Would you mind just adding your section in alphabetical order in both places? 🙏

**Comment by samuelvanderwaal** [comment]
Hi @AnnaNodes if you want this added please make the change loris requested and we'll get it merged, otherwise I will close this as stale in the next week or so.

**Comment by AnnaNodes** [comment]
Hi @lorisleiva @samuelvanderwaal 

Sorry for the long reply! I have updated the PR. 
Could you please check whether I have done everything correctly?

**Review by lorisleiva — APPROVED** [review]
Thanks!

**Comment by AnnaNodes** [comment]
Thank you for the merge!

**Pull request merged**
